version: "3"

services:

  nginx:
    image: nightz/nginx:latest
    restart: always
    hostname: nginx
    ports:
      - "8081:80"
    volumes:
      - ./deployment/nginx:/etc/nginx/conf.d
      - ./static/dist:/app/demo/dist
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "1"
